// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/texteditor/text_editor_worker.go
//
// Generated by this command:
//
//	mockgen -source internal/tools/texteditor/text_editor_worker.go
//

// Package mock_texteditor is a generated GoMock package.
package mock_texteditor

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTextEditorWorker is a mock of TextEditorWorker interface.
type MockTextEditorWorker struct {
	ctrl     *gomock.Controller
	recorder *MockTextEditorWorkerMockRecorder
	isgomock struct{}
}

// MockTextEditorWorkerMockRecorder is the mock recorder for MockTextEditorWorker.
type MockTextEditorWorkerMockRecorder struct {
	mock *MockTextEditorWorker
}

// NewMockTextEditorWorker creates a new mock instance.
func NewMockTextEditorWorker(ctrl *gomock.Controller) *MockTextEditorWorker {
	mock := &MockTextEditorWorker{ctrl: ctrl}
	mock.recorder = &MockTextEditorWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextEditorWorker) EXPECT() *MockTextEditorWorkerMockRecorder {
	return m.recorder
}

// HandleCreate mocks base method.
func (m *MockTextEditorWorker) HandleCreate(arg0 any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCreate", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCreate indicates an expected call of HandleCreate.
func (mr *MockTextEditorWorkerMockRecorder) HandleCreate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreate", reflect.TypeOf((*MockTextEditorWorker)(nil).HandleCreate), arg0)
}

// HandleInsert mocks base method.
func (m *MockTextEditorWorker) HandleInsert(arg0 any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleInsert", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleInsert indicates an expected call of HandleInsert.
func (mr *MockTextEditorWorkerMockRecorder) HandleInsert(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInsert", reflect.TypeOf((*MockTextEditorWorker)(nil).HandleInsert), arg0)
}

// HandleStrReplace mocks base method.
func (m *MockTextEditorWorker) HandleStrReplace(arg0 any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleStrReplace", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleStrReplace indicates an expected call of HandleStrReplace.
func (mr *MockTextEditorWorkerMockRecorder) HandleStrReplace(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStrReplace", reflect.TypeOf((*MockTextEditorWorker)(nil).HandleStrReplace), arg0)
}

// HandleUndoEdit mocks base method.
func (m *MockTextEditorWorker) HandleUndoEdit(arg0 any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUndoEdit", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleUndoEdit indicates an expected call of HandleUndoEdit.
func (mr *MockTextEditorWorkerMockRecorder) HandleUndoEdit(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUndoEdit", reflect.TypeOf((*MockTextEditorWorker)(nil).HandleUndoEdit), arg0)
}

// HandleView mocks base method.
func (m *MockTextEditorWorker) HandleView(arg0 any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleView", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleView indicates an expected call of HandleView.
func (mr *MockTextEditorWorkerMockRecorder) HandleView(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleView", reflect.TypeOf((*MockTextEditorWorker)(nil).HandleView), arg0)
}
